version: '3'
services:
    minecraft-server:
        container_name: minecraft
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
        tty: true
        stdin_open: true
        restart: always
        volumes:
            - ./mods:/data/mods/
            - ./data:/data/
        environment:
            EULA: "TRUE"
            VERSION: "any_version"
